<?php declare(strict_types=1); ?>
<section class="view hidden" id="view-student-dashboard" data-title="Dashboard" data-section="Student workspace">
          <div class="page-heading"><div><span class="eyebrow">TUESDAY, 8 OCTOBER 2026</span><h1>Good morning, Alex <span class="wave">*</span></h1><p class="muted">Here is what is happening around your campus.</p></div><button class="button button-primary" data-view="events">Explore events <span>* *</span></button></div>
          <div class="metric-grid"><article class="metric-card"><span class="metric-icon blue">*</span><div><strong>4</strong><span>Clubs joined</span></div><small class="positive">+1 this month</small></article><article class="metric-card"><span class="metric-icon orange">*</span><div><strong>3</strong><span>Upcoming events</span></div><small class="positive">Next one in 2 days</small></article><article class="metric-card"><span class="metric-icon purple">*</span><div><strong>12</strong><span>Events attended</span></div><small class="positive">+3 this semester</small></article></div>
          <div class="dashboard-grid"><article class="panel schedule-panel"><div class="panel-heading"><div><h2>Your upcoming events</h2><p class="muted">Do not miss out on your next experience.</p></div><button class="text-button" data-view="registrations">View all * *</button></div><div class="event-list"><div class="event-row"><div class="date-tile"><strong>10</strong><span>OCT</span></div><div class="event-info"><strong>Interfaculty Debate Night</strong><span>* 5:30 PM * Main Auditorium</span></div><span class="tag tag-blue">Registered</span></div><div class="event-row"><div class="date-tile"><strong>12</strong><span>OCT</span></div><div class="event-info"><strong>Design Thinking Workshop</strong><span>* 2:00 PM * Innovation Hub</span></div><span class="tag tag-orange">2 spots left</span></div><div class="event-row"><div class="date-tile"><strong>17</strong><span>OCT</span></div><div class="event-info"><strong>Saturday Football Social</strong><span>* 10:00 AM * Sports Grounds</span></div><span class="tag tag-green">Open</span></div></div></article><article class="panel club-panel"><div class="panel-heading"><div><h2>Your clubs</h2><p class="muted">Communities you are part of.</p></div><button class="text-button" data-view="clubs">Explore * *</button></div><div class="club-mini"><span class="club-avatar violet">*</span><div><strong>Creative Minds</strong><span>48 members</span></div><span class="online-dot"></span></div><div class="club-mini"><span class="club-avatar teal">*</span><div><strong>Tech Innovators</strong><span>126 members</span></div><span class="online-dot"></span></div><div class="club-mini"><span class="club-avatar rose">*</span><div><strong>Wellness Circle</strong><span>72 members</span></div><span class="online-dot"></span></div></article></div>
        </section>




